name: flutter_app_scaffold
description: "flutter_app_scaffold"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Core
  firebase_core: ^3.6.0
  flutter_riverpod: ^2.5.3
  riverpod_annotation: ^2.5.3
  flutter_native_splash: ^2.4.1

  # UI

  # Utility

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  custom_lint:
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/common/
    - path: assets/development/
      flavors:
        - development
    - path: assets/staging/
      flavors:
        - staging
    - path: assets/production/
      flavors:
        - production
